import 'package:flutter/material.dart';

const lightColorScheme = ColorScheme(
  brightness: Brightness.light,
  primary: Color(0xFF5F2AFF),
  onPrimary: Color(0xFFFFFFFF),
  primaryContainer: Color(0xFFE6DEFF),
  onPrimaryContainer: Color(0xFF1B0062),
  secondary: Color(0xFF5F2AFF),
  onSecondary: Color(0xFFFFFFFF),
  secondaryContainer: Color(0xFFE6DEFF),
  onSecondaryContainer: Color(0xFF1B0062),
  tertiary: Color(0xFF5F2AFF),
  onTertiary: Color(0xFFFFFFFF),
  tertiaryContainer: Color(0xFFE6DEFF),
  onTertiaryContainer: Color(0xFF1B0062),
  error: Color(0xFFBA1A1A),
  errorContainer: Color(0xFFFFDAD6),
  onError: Color(0xFFFFFFFF),
  onErrorContainer: Color(0xFF410002),
  background: Color(0xFFFFFBFF),
  onBackground: Color(0xFF1B0261),
  surface: Color(0xFFFFFBFF),
  onSurface: Color(0xFF1B0261),
  surfaceVariant: Color(0xFFE6E0EC),
  onSurfaceVariant: Color(0xFF48454E),
  outline: Color(0xFF79757F),
  onInverseSurface: Color(0xFFF4EEFF),
  inverseSurface: Color(0xFF302175),
  inversePrimary: Color(0xFFCABEFF),
  shadow: Color(0xFF000000),
  surfaceTint: Color(0xFF5F2AFF),
);

const darkColorScheme = ColorScheme(
  brightness: Brightness.dark,
  primary: Color(0xFFCABEFF),
  onPrimary: Color(0xFF30009B),
  primaryContainer: Color(0xFF4700D7),
  onPrimaryContainer: Color(0xFFE6DEFF),
  secondary: Color(0xFFCABEFF),
  onSecondary: Color(0xFF30009B),
  secondaryContainer: Color(0xFF4700D7),
  onSecondaryContainer: Color(0xFFE6DEFF),
  tertiary: Color(0xFFCABEFF),
  onTertiary: Color(0xFF30009B),
  tertiaryContainer: Color(0xFF4700D7),
  onTertiaryContainer: Color(0xFFE6DEFF),
  error: Color(0xFFFFB4AB),
  errorContainer: Color(0xFF93000A),
  onError: Color(0xFF690005),
  onErrorContainer: Color(0xFFFFDAD6),
  background: Color(0xFF1B0261),
  onBackground: Color(0xFFE5DEFF),
  surface: Color(0xFF1B0261),
  onSurface: Color(0xFFE5DEFF),
  surfaceVariant: Color(0xFF48454E),
  onSurfaceVariant: Color(0xFFC9C4D0),
  outline: Color(0xFF938F99),
  onInverseSurface: Color(0xFF1B0261),
  inverseSurface: Color(0xFFE5DEFF),
  inversePrimary: Color(0xFF5F2AFF),
  shadow: Color(0xFF000000),
  surfaceTint: Color(0xFFCABEFF),
);
